version: '3'
services:
  mongodb:
    image: mongo
    volumes:
      - mongodbdata:/data/db
    ports:
      - 27017:27017

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - mongodb

volumes:
  mongodbdata:
